
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrydedyugxtrubygfnnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyeWRlZHl1Z3h0cnVieWdmbm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjkwMDEsImV4cCI6MjA2MjU0NTAwMX0.XsKyQCZjzXsfg35vFx0txE5LIC8mjS3Us7z5vzcMk2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
